# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'elto.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(230, 350)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(230, 350))
        MainWindow.setMaximumSize(QtCore.QSize(230, 350))
        MainWindow.setBaseSize(QtCore.QSize(400, 400))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ebook.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.ServerEdit = QtWidgets.QLineEdit(self.groupBox)
        self.ServerEdit.setObjectName("ServerEdit")
        self.verticalLayout_3.addWidget(self.ServerEdit)
        self.ServiceEdit = QtWidgets.QLineEdit(self.groupBox)
        self.ServiceEdit.setEnabled(False)
        self.ServiceEdit.setObjectName("ServiceEdit")
        self.verticalLayout_3.addWidget(self.ServiceEdit)
        self.LoginEdit = QtWidgets.QLineEdit(self.groupBox)
        self.LoginEdit.setEnabled(False)
        self.LoginEdit.setInputMask("")
        self.LoginEdit.setText("")
        self.LoginEdit.setObjectName("LoginEdit")
        self.verticalLayout_3.addWidget(self.LoginEdit)
        self.PasswordEdit = QtWidgets.QLineEdit(self.groupBox)
        self.PasswordEdit.setEnabled(False)
        self.PasswordEdit.setInputMask("")
        self.PasswordEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.PasswordEdit.setObjectName("PasswordEdit")
        self.verticalLayout_3.addWidget(self.PasswordEdit)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.OpenButton = QtWidgets.QPushButton(self.groupBox_2)
        self.OpenButton.setObjectName("OpenButton")
        self.OpenButton.setEnabled(False)
        self.horizontalLayout.addWidget(self.OpenButton)
        self.pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton.setEnabled(False)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButton_2.clicked.connect(MainWindow.close)
        self.ServerEdit.textChanged.connect(lambda: self.ServiceEdit.setEnabled(True))
        self.ServiceEdit.textChanged.connect(lambda: self.LoginEdit.setEnabled(True))
        self.LoginEdit.textChanged.connect(lambda: self.PasswordEdit.setEnabled(True))
        self.PasswordEdit.textChanged.connect(lambda: self.OpenButton.setEnabled(True))
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ELTO"))
        self.groupBox.setTitle(_translate("MainWindow", "Авторизация"))
        self.ServerEdit.setPlaceholderText(_translate("MainWindow", "Введите адрес сервера"))
        self.ServiceEdit.setPlaceholderText(_translate("MainWindow", "Введите имя сервиса"))
        self.LoginEdit.setPlaceholderText(_translate("MainWindow", "Введите имя ользователя"))
        self.PasswordEdit.setPlaceholderText(_translate("MainWindow", "Введите пароль"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Выполнить"))
        self.OpenButton.setText(_translate("MainWindow", "Выбрать Файл"))
        self.pushButton.setText(_translate("MainWindow", "Загрузить"))
        self.pushButton_2.setText(_translate("MainWindow", "Выход"))
