# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Sedykhgi\Documents\GitHub\parsers\elto.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(204, 340)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(204, 340))
        MainWindow.setMaximumSize(QtCore.QSize(204, 340))
        MainWindow.setBaseSize(QtCore.QSize(400, 400))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.ServerEdit = QtWidgets.QLineEdit(self.groupBox)
        self.ServerEdit.setObjectName("ServerEdit")
        self.verticalLayout_5.addWidget(self.ServerEdit)
        self.ServiceEdit = QtWidgets.QLineEdit(self.groupBox)
        self.ServiceEdit.setObjectName("ServiceEdit")
        self.verticalLayout_5.addWidget(self.ServiceEdit)
        self.LoginEdit = QtWidgets.QLineEdit(self.groupBox)
        self.LoginEdit.setInputMask("")
        self.LoginEdit.setText("")
        self.LoginEdit.setObjectName("LoginEdit")
        self.verticalLayout_5.addWidget(self.LoginEdit)
        self.PasswordEdit = QtWidgets.QLineEdit(self.groupBox)
        self.PasswordEdit.setInputMask("")
        self.PasswordEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.PasswordEdit.setObjectName("PasswordEdit")
        self.verticalLayout_5.addWidget(self.PasswordEdit)
        self.verticalLayout_6.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.FileLine = QtWidgets.QLineEdit(self.groupBox_2)
        self.FileLine.setEnabled(False)
        self.FileLine.setObjectName("FileLine")
        self.verticalLayout.addWidget(self.FileLine)
        self.OpenButton = QtWidgets.QPushButton(self.groupBox_2)
        self.OpenButton.setObjectName("OpenButton")
        self.verticalLayout.addWidget(self.OpenButton)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton.setDisabled(True)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_3.addWidget(self.pushButton_2)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_6.addWidget(self.groupBox_2)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButton_2.clicked.connect(MainWindow.close)
        #self.FileLine.textChanged.connect(self.pushButton.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ELTO"))
        self.groupBox.setTitle(_translate("MainWindow", "Авторизация"))
        self.ServerEdit.setPlaceholderText(_translate("MainWindow", "Введите адрес сервера"))
        self.ServiceEdit.setPlaceholderText(_translate("MainWindow", "Введите имя сервиса"))
        self.LoginEdit.setPlaceholderText(_translate("MainWindow", "Введите имя ользователя"))
        self.PasswordEdit.setPlaceholderText(_translate("MainWindow", "Введите пароль"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Выполнить"))
        self.FileLine.setPlaceholderText(_translate("MainWindow", "Имя файла"))
        self.OpenButton.setText(_translate("MainWindow", "Выбрать Файл"))
        self.pushButton.setText(_translate("MainWindow", "Загрузить"))
        self.pushButton_2.setText(_translate("MainWindow", "Выход"))

